import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from '@/components/Sidebar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <div style={{ display: 'flex' }}>
          {/* 사이드바 배치 */}
          <Sidebar />

          {/* 메인 콘텐츠: 사이드바 너비(240px)만큼 왼쪽 여백을 줍니다. */}
          <main style={{ 
            flex: 1, 
            marginLeft: '240px', 
            minHeight: '100vh',
            backgroundColor: '#fff' 
          }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}